#!/usr/bin/env bash
# shellcheck disable=SC2086
# shows information about subdomains on passed in information

print_subdomain ()
{
    printf "The subdomain %s is a " "$2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf $4}'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf $5}'
}

if  [ "$2" == "$each" ]; then
    print_subdomain "$1" "$each"
else
    for each in "www" "lb-01" "web-01" "web-02"
    do
	print_subdomain "$1" each
done
	
