#!/usr/bin/env bash
#installs nginx on remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
