#!/usr/bin/env bash
#installs nginx on remote server

apt-get -y update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

ed -i 'listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
