#!/usr/bin/env bash
#installs nginx on remote server

apt-get -y update
apt-get -y install nginx
echo "Holberton School for the win!" | tee /var/www/html/index.nginx-debian.html >/dev/null
echo "Ceci n'est pas une page" | tee /var/www/html/custom_404.html >/dev/null
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/server_name _;/a error_page 404 /custom_404.html;/nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' etc/nginx/sites_available/default
service nginx start
