#!/usr/bin/env bash
#setup and installs nginx on remote server
# shellcheck disable=SC2154

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i '/permanent;/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites_available/default
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo service nginx reload
