#!/usr/bin/env bash
#setup and installs nginx on remote server
# shellcheck disable=SC2154

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i '/permanent;$/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
