#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get update
apt-get  -y install haproxy=1.6.\*
sudo printf "
frontend http_front
	 bind *:80
	 mode http
	 default_backend http_back
backend http_back
	balance roundrobin
	server 1106-web-01 35.243.245.165:80 check
	server 1106-web-02 54.243.21.33:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart