#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# and does not like to be ended
echo $$ >> /var/run/holbertonscript.pid


trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM

while true
do
    echo "To infinity and beyond"
done
