#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# and does not like to be ended
sudo bash -c 'echo $$ >> /var/run/holbertonscript.pid'
trap 'sudo rm -f /var/run/holbertonscript.pid; exit' SIGQUIT
trap 'sudo rm /var/run/holbertonscript.pid; "echo I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while true
do
    echo "To infinity and beyond"
done
