#!/usr/bin/env bash
#prints holbertonschool ten times with while
#shellcheck disable=SC2034
i=0
while [ $i -lt 10 ]
do
    if [ $i == 7 ];
    then
	echo "good luck"
	i=$((i+1))
    elif [ $i == 3 ];
    then
	echo "bad luck"
	i=$((i+1))
    else
	echo "Holberton School"
	i=$((i+1))
    fi
done
