#!/usr/bin/env bash
#prints holbertonschool ten times with while
#shellcheck disable=SC2034
i=1
while [ $i -lt 21 ]
do
    echo "$i"
    i=$((i+1))
    case $i in
	5)
	    echo "bad luck from China"
	    ;;
	10)
	    echo "bad luck from Japan"
	    ;;
	18)
	    echo "bad luck from Italy"
	    ;;
    esac
done
